# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 617d5556f86dbaaab2f56ac2132a4829b9e096200b6543630846ac282949d39fdf3bcabc9c62a93bc9f353cf8e8fa1546fffe06244813e11b4f5c0a185e6aa73

test:
  secret_key_base: 9afed8187ccf9c9a16a2f86bfa0efeab87e9327d1984e92e1e8380903e5464366193d47af21b5cf5e24fabd1b0fa216a1cb992e6c62b5b0e6d0a801d694d81ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
